### ISSUE TITLE
Introduction and a question on how to store solutions

### ISSUE THREAD

**Issue by dacre** [hankolsen/melodikryzzet#12]
Hi! 

Good job on creating melodikryzzet! I would like to use it to do melodikrysset in the summer time, but have access to all the crosswords produced during the year, including audio and solutions. Very much like the current iOS/android app, but with a much longer time span. 

I'm currently scraping melodikrysset from https://sr.korsord.se/html5/ and storing the crosswords according to the json examples use in this repo. Are you also doing that in some other project? Maybe you would be interested in that code? Currently it is unfinished and needs some cleanup. It's written in python, aiming to get it to be runnable as a crontab-job on a rpi. Also going to be storing the audio for personal use btw, possibly that I will be trying to add a feature for exposing a link to that audio in the melodikryzzet code in the future.

I'm wondering though about solutions and how to add that feature to melodikryzzet. Have you already planned for it? I see that the user data is stored in row/col, so I'm assuming the solution text should do the same? That would be a straightforward implementation since my solution source data is roughly in that form (see here for example: http://sr.korsord.se/html5/solutionview/1002). In parallell to getting my crontab scripts up and running that is my next next step.  

Best regards,
Johannes

**Comment by hankolsen** [comment]
Hi Johannes!
Thank you for your interest in the project!

Although it is called Melodikryzzet, the main idea behind the project is to provide a "crossword engine", regardless of the source of the content. It was created so that I would be able to create my own "Melodikryss"-puzzles to use at parties and gatherings with friends.

I have a side project in a very early stage, basically an Admin view, to be able to add/edit the source data in an easier way than manually creating json.

I would recommend you to use Melodikryzzet as the "engine" in any project where you can add things like audio, showing correct solutions etc etc.

Hope that makes sense
/Hank
